### ISSUE TITLE
Audapolis hangs when punctuation model is enabled

### ISSUE THREAD

**Issue by papaschloss** [bugbakery/audapolis#457]
When I try to transcribe an mp3 with the punctuation model enabled, it hangs at "90% - loading punctuation model". If I transcribe an mp3 and disable the punctuation model, it transcribes the text just fine, so it seems this is just limited to when punctuation is enable. 

This is on Win 11. Debug log attached. Let me know what else I can provide

[debug.log](https://github.com/bugbakery/audapolis/files/12148381/debug.log)

**Comment by candideu** [comment]
Same issue, Windows 10
[debug.log](https://github.com/bugbakery/audapolis/files/12175794/debug.log)

**Comment by johnblommers** [comment]
Exact same issue but on PopOS Linux.

The language is English.

**Comment by todrobbins** [comment]
Also confirming that this happens with Version 0.3.0+4 on macOS 13.5.2

**Comment by iwoolf** [comment]
Same issue in Ubuntu, installed by .deb. I thought it was just slow., but it never gets past 90%.

**Comment by alejandro5042** [comment]
Glad this was fixed in October :) Any thoughts on when it might be available on an installer?

Side note: Should this project have automated preview installer releases?
