### ISSUE TITLE
Question: Where are the models saved on the PC?

### ISSUE THREAD

**Issue by candideu** [bugbakery/audapolis#473]

**Comment by anuejn** [comment]
The models are currently saved where the [appdirs](https://pypi.org/project/appdirs/) python package would put data for a program named `audapolis` [source](https://github.com/bugbakery/audapolis/blob/10ee41a734445dd541c02c90407737ab2b529af9/server/app/config.py#L6).

**Comment by anuejn** [comment]
also see #456
